### ISSUE TITLE
[LogStage] Specify fields in JSON

### ISSUE THREAD

**Issue by gu1p** [7mind/izumi#1001]
Hey, guys! Congratulations on the job! :)

So, is there a way to specify the exact shape of each JSON line produced (eliminating fields like "template", "thread", "meta" etc)?

**Comment by neko-kai** [comment]
You need to supply a different `RenderingPolicy` for a `LogSink`, e.g. by overriding `LogstageCirceRenderingPolicy`, so instead of:

```scala
IzLogger(Log.Level.Info, Seq(ConsoleSink(LogstageCirceRenderingPolicy())))
```

instantiate with e.g.

```scala
IzLogger(Log.Level.Info, Seq(ConsoleSink(new LogstageCirceRenderingPolicy() {
  override protected def makeEventEnvelope(entry: Log.Entry, formatted: RenderedMessage): Seq[(String, Json)] = ...
})))
```

**Comment by gu1p** [comment]
Thanks @neko-kai!

**Comment by tuleism** [comment]
@neko-kai 

What's your thought on a PR to make JSON key easily overridable. For example, instead of:

```scala
if (ctx.nonEmpty) {
  result += "context" -> ctx.asJson
}
```

we have

```scala
protected val ContextKey = "context"
if (ctx.nonEmpty) {
  result += ContextKey -> ctx.asJson
}
```

**Comment by neko-kai** [comment]
@tuleism 
Sure, that would be fine

**Comment by pshirshov** [comment]
I guess I'll close this as per we are preparing 0.11 release at the moment and the fix is accepted.
