### ISSUE TITLE
Improve Activation Axis

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#1030]
There are some limitations in activation axis right now:

1. If there's a single component `make[A].from[B].tagged(Repo.Prod)` and the activation is `Repo.Dummy`, but there's no opposing `make[A].from[C].tagged(Repo.Dummy)` component, the `B` implementation will be kept, instead of resulting in an error!

2. Set elements cannot participate in Axis. Given `many[Int].add(1).tagged(Repo.Prod).add(2).tagged(Repo.Dummy)` both 1 and 2 will always be present, the only way around this currently is with a proxy binding: `many[Int].ref[Int]; make[Int].tagged(Repo.Prod).from(1); make[Int].tagged(Repo.Dummy).from(2)`

Both of these limitations should be lifted.

**Comment by pshirshov** [comment]
https://github.com/7mind/izumi/pull/845

**Comment by pshirshov** [comment]
We decided that current behavior is "good enough" as per it just allows us to define "defaults".

Though c2c084a56 allows the user to modify conflict resolution strategy with a bootstrap module.
