### ISSUE TITLE
distage-testkit: Add axes to `forcedRoots` & `memoizationRoots` in TestConfig

### ISSUE THREAD

**Issue by Caparow** [7mind/izumi#1044]
Adding axes to the DI roots will allow us to filter roots in depending on chosen axis.

E.g.
```scala
abstract class FooTest extends DistageBIOSpecScalatest[IO] {
   override protected def config: TestConfig = super.config(
      forcedRoots = Map(Set(Repo.Prod) -> Set(DIKey.get[PostgresDDL]))
   )
}

// `PostgresDDL` would be filtered from the DI roots
final class DummyRepoTest extends FooTest {
   override protected def config: TestConfig = super.config(
      activation = Activation(Repo -> Repo.Dummy, ExternalApi -> ExternalApi.Mock)
   )
  ...
}

// `PostgresDDL` would be persist in DI roots and will perform tables ddl up
final class ProductionRepoTest extends FooTest {
   override protected def config: TestConfig = super.config(
      activation = Activation(Repo -> Repo.Prod, ExternalApi -> ExternalApi.Prod)
   )
  ...
}
```

**Comment by neko-kai** [comment]
We should add Axes to `memoizationRoots` as well

**Comment by aliubymov-playq** [comment]
> We should add Axes to `memoizationRoots` as well

@neko-kai Didn't `memoizationRoots` works only for instances that persist in the final graph? 
But, that's a good idea to have Axes in memoization, to change planning policy depending on Axis (e.g. we can add a custom axis to disable or enable memorization of certain components in tests).

**Comment by Caparow** [comment]
> We should add Axes to `memoizationRoots` as well

@neko-kai Didn't `memoizationRoots` works only for instances that persist in the final graph? 
But, that's a good idea to have Axes in memoization, to change planning policy depending on Axis (e.g. we can add a custom axis to disable or enable memorization of certain components in tests).
