### ISSUE TITLE
logstage - adjust callstack (SourceFilePosition)

### ISSUE THREAD

**Issue by gu1p** [7mind/izumi#1063]
I wrapped logstage calls in my application to avoid some coupling issues, but I'm having a hard time trying to adjust the call stack (all log calls now are reported as coming from the wrapped object position).

**Comment by neko-kai** [comment]
@gustavoip 
If you use lower-level `IzLogger#log`/`LogIO#log` method instead of `info`/`warn` you can can control the reported position using a `CodePositionMaterializer` implicit. Just add it as a parameter in your methods from which you want to report the outer position:

```scala
def logAbc(log: IzLogger)(abc: Abc)(implicit pos: CodePositionMaterializer) = {
  log.log(Log.Level.Info)(s"Logging an $abc")
}

object X {
  logAbc(logger)(abc) 
  // X.scala...: Logging an abc=Abc(1, 2, 3)
}
```

**Comment by pshirshov** [comment]
@gustavoip : we don't use callstack to get code positions, they are statically introspected by our macro. I'm afraid in your case (wrapping our macro with your code) you may need to write your own macro or use @neko-kai 's workaround.
