### ISSUE TITLE
add a StandardAxis for dockerized environment, choose a name for it

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#1113]
We should export a standard configuration axis for setting up required third-party services via `distage-framework-docker`, this could be useful right away to ship `D4SDockerModule` in [d4s](https://github.com/PlayQ/d4s/blob/develop/d4s-test/src/main/scala/d4s/test/envs/D4SDockerModule.scala) in a better way than right now, using axes instead of overrides.

As requested by @pshirshov we should choose a somewhat neutral name, to allow external services to be provided in other ways than just with `distage-framework-docker` (e.g. embedded launch instead of docker)

example:

```scala
# launch app with services in local dockers

./launcher -u services:local

# launch app with production services (launched on some external remote host)

./launcher -u services:remote
```

^ the above assumes axis name `Services` & axis values `Services.Local` and `Services.Remote`

- [ ] propose other names

/cc @pshirshov @Caparow

**Comment by Caparow** [comment]
@neko-kai `Services` is good enough for me.

**Comment by neko-kai** [comment]
@Caparow 
Recently, @pshirshov proposed to call this `Scene` - it is now added to distage-example: https://github.com/7mind/distage-example/blob/develop/src/main/scala/leaderboard/axis/Scene.scala


  > Choice axis controlling whether third-party services that the application requires
  > should be provided by `distage-framework-docker` when the application starts (`Scene.Managed`),
  > or whether it should try to connect to these services normally, assuming they already exist in the environment (`Scene.Provided`)
  > 
  > The set of third-party services required by the application is called a `Scene`, etymology being that the running
  > third-party services that the application depends on are like a set-up scene which an actor (the application) then enters.

**Comment by Caparow** [comment]
@neko-kai Wow, it's really clever naming. So will you add this axis to the set of default ones?
