### ISSUE TITLE
Ambiguous reference to overloaded definition in MakeDSLBase caused by a rare mix of circumstances 

### ISSUE THREAD

**Issue by catostrophe** [7mind/izumi#1119]
I cannot even explain it with words. Here's the code:
https://scastie.scala-lang.org/catostrophe/5e41h72kSfunIIewn5VDQg

**Comment by neko-kai** [comment]
Annotating FooMaker2 fixes this https://scastie.scala-lang.org/1nPcJEE4RZ22nvcSGWgXuw

**Comment by neko-kai** [comment]
Closing. @catostrophe please reopen if this is still a problem
