### ISSUE TITLE
Tagged components lose tag when passed to function and using MagnetProvider underscore syntax

### ISSUE THREAD

**Issue by mehakun** [7mind/izumi#1178]
Izumi version 0.10.17
Given
```
trait Component[F[_]]
```
You can do
```
def ctor[F[_]](componentSpecial: Component[F] @Id("special")): Component[F] = componentSpecial

def ctor[F[_]](@Id("special") componentSpecial: Component[F] ): Component[F] = componentSpecial
      
make[Component[F]].from(ctor[F] _)
```
And
```
type SpecComp[F[_]] = Component[F] @Id("special")

def ctor[F[_]](componentSpecial: SpecComp): Component[F] = componentSpecial
      
make[Component[F]].from((c: Component[F] @Id("special")) => ctor[F](c))
```
But cannot do:
```
type SpecComp[F[_]] = Component[F] @Id("special")

def ctor[F[_]](componentSpecial: SpecComp): Component[F] = componentSpecial

make[Component[F]].from(ctor[F] _)
```
You will have runtime error _"Instance is not available in the object graph"_ because instance tag is lost somewhere. 
So it would be really nice to have type aliases and compact underscore syntax or put this problem in the caveats

**Comment by mehakun** [comment]
Also same problem when working with concrete parametrized class. I.e. I have
`final class Component[F[_]](dep: Dependency @Id("needed"))`
And add it to module with 
`make[Component[SomeIOMonad]]`

**Comment by pshirshov** [comment]
Looks like I just got into the same problem and added progression tests for it:

https://github.com/7mind/izumi/blob/d2ba8f3427b3f4de5c98ffa4e517a35745fd8122/distage/distage-core/src/test/scala/izumi/distage/injector/JSRAnnotationTest.scala#L30

I think we should try to just fallback from `apply` methods to constructors and disable all potentially broken constructs (like `.from(Smth)`, `.from(Smth.apply _)`, etc.
