### ISSUE TITLE
[LogStage] regression - circe writer writes Throwables as jsString instead of jsObject since 0.10.17

### ISSUE THREAD

**Issue by an-tex** [7mind/izumi#1204]
Caused by https://github.com/7mind/izumi/issues/1162 / https://github.com/7mind/izumi/commit/711a92babf80634a159029bd0def3bbd3a57d7cd which takes precedence over https://github.com/7mind/izumi/blob/develop/logstage/logstage-rendering-circe/src/main/scala/izumi/logstage/api/rendering/json/LogstageCirceRenderingPolicy.scala#L151

Are the predefined codecs in general interfering with that `mapScalar` function?

**Comment by an-tex** [comment]
I've added a test case demonstrating the issue: https://github.com/an-tex/izumi/commit/be54860f5eb323817d7737abbc30b91c492f80d1

When the `LogstageCodecThrowable` is removed, the test passes

**Comment by neko-kai** [comment]
@an-tex Thank you very much! I've opened a PR with the fix & your commit https://github.com/7mind/izumi/pull/1206

**Comment by an-tex** [comment]
Thanks for fixing it so quickly @neko-kai ! I've tested it with 0.10.19, works like a charm! Now elasticsearch is happy again ;)
Btw a github release for that one is missing.
