### ISSUE TITLE
Sound behaviour for tagged Set elements?

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#1221]
From https://github.com/7mind/izumi/issues/1030:

* Set elements cannot participate in Axis. Given
  ```scala
  many[Int]
    .add(1).tagged(Repo.Prod)
    .add(2).tagged(Repo.Dummy)
  ```
  both 1 and 2 will always be present, the only way around this currently is with a proxy binding:
  ```scala
   many[Int].ref[Int]
   make[Int].tagged(Repo.Prod).from(1)
   make[Int].tagged(Repo.Dummy).from(2)
   ```

The above can actually be regarded a syntactic issue. Forbidding tagging of set elements will forbid the first (non-sensical) code example from being written.

**Comment by pshirshov** [comment]
Done
