### ISSUE TITLE
BIO: test built-in BIO* instances using cats-effect Laws

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#1245]
Since we can convert BIO to cats easily, we should add tests that check all `ConcurrentEffect` laws pass for any `F[+_, +_]: BIOAsync: BIORunner`

This was almost done before but there were binary incompability problems with `discipline` & `scalatest` at the time. These should be fine by now: https://github.com/7mind/izumi/blob/develop/fundamentals/fundamentals-bio/src/test/scala/izumi/fundamentals/bio/MiniBIOCatsLaws.scala

/cc @VladPodilnyk

**Comment by VladPodilnyk** [comment]
@neko-kai, I'll take it if it's still free. Could I assign it for myself?

**Comment by neko-kai** [comment]
@VladPodilnyk Sure, I assigned you 👍

**Comment by VladPodilnyk** [comment]
Thanks!
