### ISSUE TITLE
distage-framework-docker: cannot use local images or launch without network access to `docker-v1.registry.com`

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#1253]
See reproduction project: https://github.com/vilunov/izumi-test-docker

### Steps to reproduce

- Create an image tagged with `example.com/unknown/image:1337`

```sh
docker pull busybox:latest
docker tag busybox:latest example.com/unknown/image:1337
```

- Make sure it works outside Distage

```sh
docker run --rm example.com/unknown/image:1337
```

- Run the test

```sh
sbt test
```

### Expected

Launch, reusing existing `example.com/unknown/image:1337` image

/cc @vilunov

### Actual

Exception on `docker pull`

**Comment by neko-kai** [comment]
A related issue is that `distage-framework-docker` tests do not launch in offline mode, due to `docker pull` action always wanting to connect successfully to docker registry – we should ignore network failure in this case instead.

**Comment by pshirshov** [comment]
@vilunov : is it still broken?

**Comment by vilunov** [comment]
Not for me, I just disable pulling images via the new `alwaysPull` configuration parameter.
