### ISSUE TITLE
Add build for GraalVM native image in `distage-example`

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#1261]
See 
https://github.com/7mind/distage-example/issues/109#event-3780304111

Just need to move code changes from here - https://github.com/7mind/izumi/pull/1185/files -  to `distage-example`

**Comment by neko-kai** [comment]
This https://github.com/7mind/distage-example/pull/265 is merged, what else is left?

**Comment by pshirshov** [comment]
There is still a [bug](https://github.com/oracle/graal/issues/4282) preventing localhost docker connections from working but this one is done.
