### ISSUE TITLE
Use cats-effect 3

### ISSUE THREAD

**Issue by stevejb71** [7mind/izumi#1533]
I upgraded my project to cats-effect 3.0, but it fails at runtime from QuasiIO, NoClassDefFoundError on cats.effect.Sync

**Comment by VladPodilnyk** [comment]
Hi @stevejb71!
Unfortunately, now you cannot use Izumi with CE3, since CE3 introduce some breaking changes.
Here is related issue https://github.com/7mind/izumi/issues/1468

**Comment by stevejb71** [comment]
Thanks for the quick response. 
I guess this can be closed as a duplicate?
Do you have a timeline for supporting CE3?

**Comment by VladPodilnyk** [comment]
@stevejb71, it's planned to be in `1.1`, but @neko-kai should know for sure.

**Comment by VladPodilnyk** [comment]
@stevejb71, I'll close this. You can track progress and ask question related to CE3 support in https://github.com/7mind/izumi/issues/1468

Thanks!
