### ISSUE TITLE
Upgrade Distage & Logstage to ZIO 2.0

### ISSUE THREAD

**Issue by swoogles** [7mind/izumi#1617]
Note - I am not familiar with these projects. It might make more sense to migrate them to 2.0 separately, but I just want to initiate the discussion and hopefully get some feedback from the more knowledgeable maintainers!

ZIO 2.0 is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.0.0-M4

The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
zio/zio#5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala
We highly recommend starting with that, and then working through any remaining compilation errors :)

To assist with the rest of the migration, we have created this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

If you would like assistance with the migration from myself or other ZIO contributors, please let us know!

**Comment by pshirshov** [comment]
Hi,

I guess this issue had been created semi-automatically.

izumi does not depend on zio directly, it has BIO, a TF abstraction layer. Izumi also works with monix and cats-effect.

A P/R with BIO port to 2.0 would be much appreciated, seems like it's of some importance for some people including @jdegoes: https://github.com/zio/interop-cats/issues/426#issuecomment-954073647

We can't work on that at the moment, though would be very grateful for a P/R.

**Comment by williamareynolds** [comment]
Is there any chance we could get a prerelease of the scala 3 libraries published? I see them in snapshots, and I can successfully use them as I need them in projects I'm working on, but I'd love to be able to run some proper prototypes without having to worry about flaky builds.

**Comment by pshirshov** [comment]
There will be a milestone release soon.

**Comment by neko-kai** [comment]
@williamareynolds `1.1.0-M15` for Scala 3 is now live on maven central

**Comment by lukoyanov** [comment]
Could you guys please advise if there will be support for ZIO 2 in distage version 1.2 or future versions? Is anyone currently working on this?

We currently use distage + ZIO 1 in our projects, but we are considering upgrading to ZIO 2, possibly this year.

**Comment by pshirshov** [comment]
It's WIP, just wait.

**Comment by neko-kai** [comment]
Fixed in https://github.com/7mind/izumi/releases/tag/v1.1.0-M24
