### ISSUE TITLE
finish Injector refactoring: replace all exceptions with Either

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#1786]
@pshirshov

**Comment by pshirshov** [comment]
I've removed all the unnecessary exceptions and internal usages of `planUnsafe` (former `plan`), the uses which are still there have to throw anyway, so it's ok to leave it as it is.

One use may be removed if we support bindings like `fromEither`:

```scala
  make[AppStartupPlans].from {
    (roleAppPlanner: RoleAppPlanner, roots: Set[DIKey] @Id("distage.roles.roots")) =>
      roleAppPlanner.makePlan(roots)
  }
```

`makePlan` may return `Either` here but that would be useless unless we have `.fromEither`.
