### ISSUE TITLE
Private bindings

### ISSUE THREAD

**Issue by pshirshov** [7mind/izumi#1968]
We might want to support "private" bindings which would never be exposed in `Locator`s produced by the interpreter. 

It might be useful to, for example, hide bootstrap context members from the rest of the application.

Alternatively we might hide _everything_ apart from the graph roots and an optional list of "public" keys.

We should add a way to tell `produce` to respect private declarations and this should be on by default. There still may be situation when user might want to make everything public.

**Comment by neko-kai** [comment]
We might want to declare 'privateness' on memoization level itself, not on the module. So e.g. we want docker memoization level to not pass on Clock instance further, but we don't want Clock to be non-singleton on every single level of memoization.

**Comment by lukoyanov** [comment]
Sounds like a great feature 👍

**Comment by neko-kai** [comment]
Fixed in https://github.com/7mind/izumi/pull/2162
