### ISSUE TITLE
Is there an example of a basic leader board service using GRPC exposed API?

### ISSUE THREAD

**Issue by alexmtrmd** [7mind/izumi#2016]

**Comment by neko-kai** [comment]
@alexmtrmd No, but if there was it wouldn't be substantially different from any other GRPC example. In https://github.com/7mind/distage-example we use http4s for the http API, in a similar example for grpc you'd use the grpc library as normal, i'd expect all the distage-specific parts to be broadly the same whether you use http or gprc.
