### ISSUE TITLE
Specific support for Success/Failure alternatives in method outputs

### ISSUE THREAD

**Issue by pshirshov** [7mind/izumi#211]
It's a very good idea to translate

```
def method(...) => Success | Failure
```

into something like

```
def method(...): OurEither[Failure, Success]
```

Open question: when to do that, which order to use, etc.

Maybe we need a special syntax like

```
def method(...) => Failure \/ Success
def method(...) => Success / Failure
def method(...) => Success or Failure
```
?

We may

1. Introduce new container type, like `IRTEither`, similar to `IRTResult` with an appropriate interface
2. Add new branches into `{typed|raw}.Service.DefMethod.Output`
3. Support it in parser 
4. Support in scala renderer
5. Use standard ADT handlers for all the non-scala transpilers
6. We need to ship at least one implementation for `IRTEither`

As primary implementation of `IRTEither` we may use:

1. https://github.com/scalaz/ioeffect (I have some hope for it)
2. `IO[Either[_, _]]`
3. `EitherK` from https://github.com/frees-io/iota with 3 branches, like `EitherK[Success, Failure, Exception]` with our own exception handling
4. Same stuff but with Shapeless/any other container
5. https://github.com/pshirshov/izumi-r2/pull/95

**Comment by pshirshov** [comment]
Syntax:

```
  def greetAlgebraicMultilineCurlyBracesSyntax
   {
     firstName: str
     secondName: str
   } => {
     SuccessData
   } !! {
     ErrorData
   }

   def alternative(firstName: str, secondName: str) => SuccessData !! ErrorData
   def voidAlternative(firstName: str, secondName: str) => () !! ()
```

**Comment by pshirshov** [comment]
Almost there, we need to fix go/csharp/ts transpilers.

**Comment by InfiniteCode** [comment]
Implemented in C#, Go, and TS.

C# and Go fall back to regular adts with extra helper methods.
TS generates a helper Adt + uses IRT class Either<L, R> which provides a few helpers.
