### ISSUE TITLE
Think about non-singleton binding semantic

### ISSUE THREAD

**Issue by pshirshov** [7mind/izumi#24]
At one hand we resolve at with factories, at the other hand it still may be convenient. Some ideas:

1. `@Prototype` annotation at usage point
2. Non-singleton binding and non-singleton key (prototype key)

Note: factories are different. Also I don't have any sane usage scenario for this at the moment, but let's keep it.

**Comment by neko-kai** [comment]
IMHO my mental model of a DI framework is that it just lifts the `import` statement from package-level to class-level... In that model, non-singleton bindings are unsound - you can't import same package twice and get different instances!

**Comment by pshirshov** [comment]
We never needed it so far. Let's close.
