### ISSUE TITLE
Implement bindings returning for Multiple Set Elements.

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#276]
i.e.
```scala
trait A
case class B(val1: A, val2: A)

make[B]

many[A].from {
   b: B=>
       Set(b.val1, b.val2)
}
```

1. Add a new Binding, MultiElementBinding
2. Add a new ExecutableOp, AddMultipleElements and/or add a { wiring: UnaryWiring } field to CreateSet, that would supply the set with initial elements
3. Add test, esp. for circular dependencies handling
4. Extend current GC tests to make sure it works for all the cases including weak refs.

**Comment by pshirshov** [comment]
New operation isn't required, I've solved it with some minor changes in `SetStrategyDefaultImpl`

**Comment by pshirshov** [comment]
Seems like the rest can be done easily:
This:

```
many[A].from {
   b: B=>
       Set(b.val1, b.val2)
}
```

Should create two bindings:
1) `generated_key := Set(b.val1, b.val2)`
2) `Set[A] += Reference(generated_key)`

So, we should just allow user to use `Reference[Set[A]]` as `Set[A]` element (weak option should be exposed too).

Unfortunately, we have a language limitation:

```
    final def ref[I <: T : Tag](implicit pos: CodePositionMaterializer): AfterAdd =
```

We cannot say `(I || Set[I]) where I <: T  `.

So I would propose this syntax:

```
many[A].subset.from {
   b: B=>
       Set(b.val1, b.val2)
}
many[A].subset.from(Set(1, 2))
many[A].subset.fromWeak(Set(1, 2))
many[A].subset.ref[Key]
many[A].subset.weak[Key]
```

**Comment by neko-kai** [comment]
> We cannot say (I || Set[I]) where I <: T.

We can just say 

```scala
final def ref[I <: Set[T]](implicit pos: CodePositionMaterializer, dummy: DummyImplicit): AfterAdd
```
