### ISSUE TITLE
Publish separate doc sites for latest release and develop

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#322]
Instead of publishing docs just for current `SNAPSHOT`, we should have docs for stable version too (mainly to get correct sbt commands to import into project)

**Comment by pshirshov** [comment]
Done.

At the moment during each site publishing I'm preserving all the release docs in their subdirs, dropping all the snapshot docs and creating a new subdir for current snapshot.

More work needs to be done: `index.html` needs to be improved (and maybe autogenerated, it's possible), some nice resources should be put into `/media` directory (it's being preserved as well).
