### ISSUE TITLE
Tag macro: remaining work

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#374]
* <strike>replace parameters in HKT: `[T: Tag] => Either[T, ?]` this means adding a macro case to HKTag and appropriate logic in TagMacro [i.e. extracting the real param from `{ type Arg }`.</strike> done
* replace parameters in structural types: `{ def x: T ; type Y = G }`. Keep generating weak type tags for structural part, in runtime, mutate the symbols inside `MemberScope` of a weak tag holding the structural with `.setInfo` – set their types to resolved parameters from `Tag`
* Replace parameters in type bounds `_ >: G <: T`. ( & existentials? steal code from shapeless)
* Make `TagKUBound` work. In macro, replace `kindOf` and `Kind` type with a more sophisticated check, also preserving type bounds so that we can summon the appropriate instance together with type bounds in `summonTag`

related #369 #350

**Comment by neko-kai** [comment]
Addendum: Replace parameters in type projections: `def x[A <: X: Tag] => A#Component`, including when prefix is a singleton: `x[a.type] => a.Component // if `a` is a static object, not a free term`

**Comment by pshirshov** [comment]
Having `TagKK[F[A, B]]` should provide us `TagK[F[Something, ?]]`

**Comment by neko-kai** [comment]
`HKTag` resolving is fixed. The other enhancements are split into new issues:

https://github.com/7mind/izumi/issues/771
https://github.com/7mind/izumi/issues/772
https://github.com/7mind/izumi/issues/773
