### ISSUE TITLE
ModuleBase ++ stopped working for user subclasses

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#391]
We have a a basic example in documentation:

```scala
trait Hello
object HelloModule extends ModuleDef {
  make[Hello]
}

trait Bye
object ByeModule extends ModuleDef {
  make[Bye]
}

val helloBye = HelloModule ++ ByeModule
```

Which doesn't compile anymore after the introduction of `ModuleMake` typeclass – there's no instance for HelloModule.

`ModuleMake` was introduced to prevent mixing between Modules, Plugins and Bootstrap Modules.

I see two solutions here:

1. Remove `ModuleMake`, and add a discriminator type parameter / type member to `ModuleBase`, ++ will no longer preserve the subtype of ModuleBase, but it will preserve the discriminator:
    ```scala
    trait ModuleBase[+Type <: ModuleType]
  
    type Module = ModuleBase[IsModule]
    type BootstrapModule = ModuleBase[IsBootstrapModule]
    type PluginBase = ModuleBase[IsPlugin]
  
    private trait ModuleType
  
    trait IsBootstrapModule extends ModuleType
    trait IsModule extends ModuleType
      trait IsPlugin extends IsModule
  
    def ++[T](self: ModuleBase[T])(that: ModuleBase[T]): ModuleBase[T]
    ```
2. Introduce an F-Bound on ModuleBase and lookup `MkModule` type class instances not by the type of module value, but by it's F-bound. This will up-cast user's sub-classes to the nearest type:
    ```scala
    trait ModuleBase {
      type Self = ModuleBase
    }
    
    trait Module extends ModuleBase {
      override type Self = Module
    }
    
    trait BootstrapPlugin extends ModuleBase {
      override type Self = BootstrapPlugin
    }
    
    trait Plugin extends Module {
      override type Self = Plugin
    }
    
    def ++(self: ModuleBase)(that: ModuleBase { type Self <: self.Self })(implicit mk: ModuleMake[self.Self]): self.Self
    ```

**Comment by pshirshov** [comment]
I would go with (2)
