### ISSUE TITLE
BIO syntax updates purpose

### ISSUE THREAD

**Issue by ratoshniuk** [7mind/izumi#494]
can we have follow method for BIO?

`leftFlatMap` => it performs redeem logic, but prevents to map right side into `identity`

`flip` (or another literal) => swaps Left and Right

flips could help us to prevent map asBad and other related stuff for tests

**Comment by ratoshniuk** [comment]
@pshirshov @kaishh

**Comment by neko-kai** [comment]
Your PR has been merged 👍
