### ISSUE TITLE
Split BIO into traits 

### ISSUE THREAD

**Issue by ratoshniuk** [7mind/izumi#500]
@kaishh , do we always need to tag BIO as an Interface of whole methods? 

Maybe we could split it up as BIOMonad, BIOFunctor, BIOEffect, etc

**Comment by neko-kai** [comment]
We should probably do that, but why not put your energy into cats-effect 2.0 instead?
- [Cats Effect 2.0 Design Discussion](https://github.com/typelevel/cats-effect/issues/321)
- [Prototype cats effect 2.0](https://github.com/scalaz/scalaz-zio/issues/565)

BIO is just a thin wrapper around zio, it's not an abstraction. (atm at least)
