### ISSUE TITLE
Distage: split testkit memoizer collection to local and global

### ISSUE THREAD

**Issue by Caparow** [7mind/izumi#503]
Splitting memoizer on two independent collections (test suit based and global) will help to avoid false positives when wrong instance was memoized. (e.g if we save ran dummy DB persistence test firstly and then production - we will test dummy persistence twice because target type already exists in memoizer collection).

Test suit memoizer would save suit based instances (like repositories etc.) and global memoizer would save global instances (like DB connectors, DDL, etc.). Also test suit based memoizer should help speed up parallel tests execution.

**Comment by pshirshov** [comment]
I guess the only way to solve the problem completely is to implement our own test framework which will have global knowledge and plan all the work ahead of time.

**Comment by pshirshov** [comment]
I've provided disambiguating logic, and completely reworked memoization in #518 so thigs shouldn't be an issue anymore.

Though the logic is still imperfect and we can't implement an ideal solution unless we:

1. Stop using tags and switch to more restrictive model (#292)
2. Implement our own test framework so we may build all test plans ahead of time
