### ISSUE TITLE
LogSink[F[_]] 

### ISSUE THREAD

**Issue by ratoshniuk** [7mind/izumi#508]
```scala
trait LogSink[F[_]] {
   def flush(entry: Entry) : F[Unit] = ???
}
```

**Comment by pshirshov** [comment]
At this point I'm not sure if we still need this. If we decide to implement this, it would be necessary to support `LogRouter[F[_]]`.

Alternatively we may just provide some extension points to make it easier to provide implementations for `AbstractLogIO#log`
