### ISSUE TITLE
Try to use refcounting to optimise GC phase

### ISSUE THREAD

**Issue by pshirshov** [7mind/izumi#532]
We may count references while building plan and apply basic cleanups without running full tracer

**Comment by neko-kai** [comment]
The idea is to run a first pass over all plan nodes and count the times each DIKey is used as a parameter. This can prune nearly all non-circular cases immediately, leaving less keys for `TracingDIGc` to process.

A newcomer may take this ticket.

**Comment by pshirshov** [comment]
I guess this is not relevant anymore since the introduction of `SemigraphSolver`. The tracer is, essentially, still there (`traceGrouped`) though I doubt we may achieve any sensible performance gains with additional "ref-counting" pass over the initial input. I'll close this for now.
