### ISSUE TITLE
Deprioritize creating proxies for bindings that are used by effects/resources within a dependency cycle

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#663]
Because effects/resources will almost always use the proxy immediately. Instead, possibly, assign higher priority to results of effects themselves...

**Comment by neko-kai** [comment]
Also when cycle-breaking using by-names is possible, by-names should always be chosen.

Possibly: disable proxies by default, when cycle is detected print advise to add by-names to a list of targets

**Comment by pshirshov** [comment]
Actually this was done in c767bc39bd5d42478f08f353f925e3c70035eea4.
