### ISSUE TITLE
ZIO v1.0.0-RC17 and LogStage 0.9.12

### ISSUE THREAD

**Issue by IvanDyachenko** [7mind/izumi#735]
I'm not sure if the problem is with Logstage. But after update `zio/zio` to `v1.0.0-RC17` and `zio/interop-cats` to `v2.0.0.0-RC8` have started getting such error:

```bash
╠─An unchecked error was produced.
║ java.lang.NoSuchMethodError: zio.Fiber$Descriptor.id()J
║     at logstage.LogstageZIO$$anon$1.$anonfun$wrap$2(LogstageZIO.scala:21)
║     at zio.internal.FiberContext.evaluateNow(FiberContext.scala:386)
║     at zio.internal.FiberContext.$anonfun$fork$2(FiberContext.scala:655)
║     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
║     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
║     at java.lang.Thread.run(Thread.java:748)
```

`logstage-core` version is `0.9.12`.

Full log: https://gist.github.com/IvanDyachenko/3e7d5155a581ce2897456f4da36cac50

**Comment by neko-kai** [comment]
@IvanDyachenko RC17 broke binary compatibility with RC16. This needs a new version of izumi to build against RC17. (For now, you may disable FiberId logging by using `LogIO.fromLogger` instead of LogstageZIO - that would avoid ZIO-specific code and avoid this error)

**Comment by neko-kai** [comment]
@IvanDyachenko @0x736861
Version `0.9.13` is published on maven central. It depends on ZIO `1.0.0-RC17`, upgrading should fix your issue.

**Comment by IvanDyachenko** [comment]
@neko-kai  Thanks!
