### ISSUE TITLE
Change syntax for binding to multiple interfaces

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#753]
Using a separate keyword `bind` feels odd. Instead we could extend the main `make` builder to create additional references at the end.

I think we may change multiple binding syntax from:
```
bind[ImplXYZ].to[X].to[Y].to[Z]
```
to
```
make[XYZ].named("myXYZ").from[ImplXYZ]
  .alias[X]
  .alias[Y]
  .alias[Z]
```

/cc @VladPodilnyk

**Comment by VladPodilnyk** [comment]
@neko-kai,  IMO, `bind[...].to[...]` construction is pretty straightforward, but `the new` syntax might have better readability.
Also, I could approach this.

**Comment by neko-kai** [comment]
@VladPodilnyk Sure, feel free to! 👍
