### ISSUE TITLE
Document Docker Resources

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#761]
There is some documentation in the [release notes for 0.9.13](https://github.com/7mind/izumi/releases/tag/v0.9.13) and there's an [example PR](https://github.com/7mind/distage-livecode/pull/2/files) showing how to use them. However, it would be great to have a dedicated chapter on the [microsite](https://izumi.7mind.io) about Docker resources.

Release notes copied below:

Docker containers can now be declared as test dependencies / Resources in `distage-testkit`:

```scala
object PostgresDocker extends ContainerDef {
  val primaryPort: DockerPort = DockerPort.TCP(5432)

  override def config: Config = {
    ContainerConfig(
      image = "library/postgres:latest",
      ports = Seq(primaryPort),
      reuse = true,
    )
  }
}
```

Dependencies can be declared between docker containers:

```scala
object DockerPlugin extends DockerContainerModule[zio.Task] with PluginDef {
  // this container will start once `DynamoContainer` is up and running
  make[PostgresDocker.Container].fromResource {
    PostgresDocker.make[zio.Task]
      .dependOnDocker(DynamoDocker)
  }
}
```

Use in test:

```scala
class DBTest extends DistageBIOSpecScalatest[zio.IO] {
  "postgres docker" should {
     "respond to queries" in {
        (doobie: Transactor[zio.Task], pg: PostgresDocker.Container) =>
          doobie.trans.apply(sql"select 1")
     }
  }
}
```

**Comment by coreyoconnor** [comment]
As documentation was released as part of 0.10.15: Closing this issue in favor of specific issues covering new features. Feel free to re-open if that's not appropriate :)
