### ISSUE TITLE
Wire RoleAppStarter & TestEnvironment with distage itself

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#779]
`RoleAppStarterImpl` & `TestEnvironmentImpl` both use a sort of bespoke thin cake to wire themselves, for no good reason as far as I can tell. Switching to wiring their internal graph with distage would improve both maintainability and extensibility (and reduce number of input parameters to 1 - just the input `ModuleBase`)

**Comment by pshirshov** [comment]
Done in #1208 

Though it's still a good idea to do the same for `distage-testkit`
