### ISSUE TITLE
Configwriter: deletes named config instances during minimization

### ISSUE THREAD

**Issue by Caparow** [7mind/izumi#798]
Plugin:
```scala
  makeConfigNamed[SomeCfg]("path")
  make[SomeCfg].from {
    (conf: SomeCfg @Id("path")) =>
      SomeCfg.adjustConfig(conf): SomeCfg
  }
```

*Expected result*: minimized config would have `path` section.
*Actual result*: `path` section has been deleted from minimized config.

**Comment by pshirshov** [comment]
I've tried to reproduce the issue in 526541aff though it works for me. I guess I need a repro.

Here is the test: https://github.com/7mind/izumi/blob/develop/distage/distage-framework/src/test/scala/izumi/distage/roles/test/RoleAppTest.scala#L201
Here are the fixtures: https://github.com/7mind/izumi/blob/develop/distage/distage-framework/src/test/scala/izumi/distage/roles/test/fixtures/TestPlugin.scala#L45
