### ISSUE TITLE
Easier creation of custom rendering policies in logstage

### ISSUE THREAD

**Issue by mflis** [7mind/izumi#814]
Hi,

I needed to slightly modify output json log, to conform to Stackdriver log format. I saw that only implemented json rendering policy `LogstageCirceRenderingPolicy` contains a lot of intricate private inlined methods. Are they private and inlined because of performance considerations? If not, I would recommend to expose them somehow, to allow easier implementation of custom rendering policies.

For now I ended up copying whole existing class and changing what I needed, but that's not an elegant solution.

**Comment by pshirshov** [comment]
> Are they private and inlined because of performance considerations? 

Yup. The performance impact is nearly negligible comparing to circe overhead but logger methods can easily be hotspots so we decided to save a bit.

> to allow easier implementation of custom rendering policies

Ok, I think we'll do it. Also patches are very welcomed here :3

**Comment by neko-kai** [comment]
@mflis The methods in question are not private anymore in version `0.10.0`

**Comment by mflis** [comment]
Thanks a lot.
