### ISSUE TITLE
Think about storing custom annotations to be read by user extensions

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#906]
After version `distage` `0.10`, `SymbolInfo` no longer contains trees for all the annotations on the symbol (because we can't depend on `scala-reflect`, so we can't represent trees)
That means user-defined `PlannerHook`'s cannot read custom annotations from symbols to rewrite plans based on them, this limits the extensibility ceiling of the framework.

We could re-add support for custom annotations using a mechanism similar to `shapeless.Annotation` – we could splice trees to call `new` of the annotation classes and store them in `SymbolInfo`, that would allow access to annotation values for all the extension needs.

However, for now izumi core libraries themselves do not require this functionality, so it may be postponed.

If you need this, please comment on this issue! It may be addressed quickly if there's actual demand.

**Comment by pshirshov** [comment]
I guess we may just close this for now. There is no more PlanningHook.
