### ISSUE TITLE
distage-framework-docker: Do not duplicate containers spawning in parallel when `reuse=true`

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#945]
Currently even when `reuse` is turned on, containers may be duplicated under parallel tests when they launch at the same time, because their spawning is non-atomic.

Current plan: use `nio.FileLock` in temporary directory to signify that a reusable container is spawning and prevent duplicates from spawning

**Comment by Caparow** [comment]
@neko-kai may you take a glance at my solution? PR #961
