### ISSUE TITLE
fundamentals-bio: Add monix-bio instance

### ISSUE THREAD

**Issue by neko-kai** [7mind/izumi#970]

**Comment by VladPodilnyk** [comment]
@neko-kai I'd like to approach this. Just to clarify, we need to do smth like this https://github.com/7mind/izumi/blob/develop/fundamentals/fundamentals-bio/src/main/scala/izumi/functional/bio/impl/BIOAsyncZio.scala ?

**Comment by neko-kai** [comment]
@VladPodilnyk Yep

**Comment by VladPodilnyk** [comment]
Ok, thanks

**Comment by VladPodilnyk** [comment]
closed by https://github.com/7mind/izumi/pull/996
