### ISSUE TITLE
logstage: handling of optional arguments

### ISSUE THREAD

**Issue by an-tex** [7mind/izumi#975]
Would it make sense to handle optional arguments like this:

```scala
val name = Option("myName")
val age = Option.empty[Int]
izLogger.info(s"$name $age")
```
currently prints
`name=Some(myName) age=None`
how about having it just print
`name=myName`

My usecase is a rate-logger with an optional "total" argument, so the log looks either like:

- no known total: `rate=8/s done=14`
- with known total: `rate=8/s done=14 left=238 donePercent=5%`

**Comment by neko-kai** [comment]
@an-tex 
Eh, that would be pretty hard to do automatically. But you can emulate this behavior like this:

```scala
import logstage.Message

val emptyMessage = Message("")
val message = 
  name.fold(emptyMessage)(name => Message(s"$name")) +
  age.fold(emptyMessage)(age => Message(s" $age"))

izLogger.log(Log.Level.Info)(message)
```

**Comment by an-tex** [comment]
Ah thx! I wasn't aware of the Message constructor. That should do the job for now. Due to the labels you added I guess you think it's still worth pursuing? I'd pick it up if the workaround is getting too messy in my code. Otherwise feel free to close it. Awsm libarary btw, makes logging and searching in Kibana so easy :)

**Comment by neko-kai** [comment]
@an-tex 
Definitely feel free to pursue this! Although do try to make it configurable as not everyone might want such behavior by default.

**Comment by pshirshov** [comment]
I think this should be implemented at rendering policy level.

For json policy this can be achieved by customising circe's Printer (there is an option to skip nulls), for string policy we may add a parameter for this. 

Also there is an argument flag to suppress argument names, we may add one more flag (or turn existing one into an ADT) so we may adjust None/null suppression at for each individual argument.

**Comment by an-tex** [comment]
The suggestion regarding the rendering policy by @pshirshov makes most sense. I won't pursue it any further. From my side the issue can be closed or do you want to keep it around @neko-kai ?

**Comment by neko-kai** [comment]
I think in that case we may close it.
